In [6]:
import tensorflow as tf

def cost(hypothesis, Y):
    return tf.reduce_mean(tf.square(hypothesis - Y))

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

x1 = tf.Variable(0.0)
x2 = tf.Variable(0.0)
x3 = tf.Variable(0.0)
Y = tf.Variable(0.0)

#[1]은 w에 하나의 값을 가진다는 것을 의미
w1 = tf.Variable(tf.random.normal([1]), name='weight1')
w2 = tf.Variable(tf.random.normal([1]), name='weight2')
w3 = tf.Variable(tf.random.normal([1]), name='weight3')
b = tf.Variable(tf.random.normal([1]), name='bias')


optimizer = tf.optimizers.SGD(learning_rate=1e-5)

for step in range(2001):
    with tf.GradientTape() as tape:
        hypothesis = x1_data * w1 + x2_data * w2 + x3_data * w3 + b
        curr_cost = cost(hypothesis, y_data)

    gradients = tape.gradient(curr_cost, [w1, w2, w3, b])
    optimizer.apply_gradients(grads_and_vars=zip(gradients, [w1, w2, w3, b]))

    if step % 10 == 0:
        print(step, "Cost: ", curr_cost.numpy(), "\nPrediction:\n", hypothesis.numpy())

#이 방법은 잘 사용되지 않음, matrix 이용

0 Cost:  6377.112 
Prediction:
 [ 84.37232   96.8017    97.6126   107.951485  71.33961 ]
10 Cost:  13.10363 
Prediction:
 [154.92964 181.6304  181.1833  198.95865 136.04791]
20 Cost:  12.984375 
Prediction:
 [155.13048 181.89578 181.43236 199.23062 136.25568]
30 Cost:  12.92363 
Prediction:
 [155.11845 181.90527 181.4293  199.22806 136.26826]
40 Cost:  12.863249 
Prediction:
 [155.10585 181.914   181.42554 199.22469 136.28023]
50 Cost:  12.803186 
Prediction:
 [155.09328 181.9227  181.42178 199.22134 136.29218]
60 Cost:  12.743422 
Prediction:
 [155.08075 181.93138 181.41801 199.218   136.3041 ]
70 Cost:  12.683996 
Prediction:
 [155.0682  181.93999 181.41423 199.21461 136.31593]
80 Cost:  12.624875 
Prediction:
 [155.05574 181.94861 181.41049 199.21129 136.32779]
90 Cost:  12.566107 
Prediction:
 [155.0433  181.9572  181.40678 199.20796 136.3396 ]
100 Cost:  12.507622 
Prediction:
 [155.0309  181.96579 181.40308 199.20465 136.35138]
110 Cost:  12.449443 
Prediction:
 [155.01852 181.97

In [13]:
def cost(hypothesis, Y):
    return tf.reduce_mean(tf.square(hypothesis - Y))

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]

y_data = [[152.], [185.], [180.], [196.], [142.]]

#shape를 이용하지 않기 때문에 이렇게 수정해줌
X = tf.constant(x_data, dtype=tf.float32)
Y = tf.constant(y_data, dtype=tf.float32)

W = tf.Variable(tf.random.normal([3, 1]), name='weight3')
b = tf.Variable(tf.random.normal([1]), name='bias')

for step in range(2001):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(X, W) + b
        curr_cost = cost(hypothesis, y_data)
    gradients = tape.gradient(curr_cost, [W, b])
    optimizer.apply_gradients(grads_and_vars=zip(gradients, [W, b]))

    if step % 10 == 0:
        print(step, "Cost: ", curr_cost.numpy(), "\nPrediction:\n", hypothesis.numpy())

0 Cost:  80762.87 
Prediction:
 [[ -95.85604 ]
 [-121.7444  ]
 [-116.481415]
 [-127.552025]
 [ -94.01371 ]]
10 Cost:  13.218023 
Prediction:
 [[155.50833]
 [180.40244]
 [181.21573]
 [196.63406]
 [136.45346]]
20 Cost:  12.412714 
Prediction:
 [[156.2554 ]
 [181.3259 ]
 [182.11234]
 [197.61182]
 [137.16304]]
30 Cost:  12.346972 
Prediction:
 [[156.2442 ]
 [181.33792]
 [182.11095]
 [197.61168]
 [137.17743]]
40 Cost:  12.281634 
Prediction:
 [[156.23077]
 [181.34717]
 [182.10686]
 [197.60858]
 [137.18968]]
50 Cost:  12.216656 
Prediction:
 [[156.21735]
 [181.35635]
 [182.10275]
 [197.60547]
 [137.20187]]
60 Cost:  12.15197 
Prediction:
 [[156.20398]
 [181.36557]
 [182.0987 ]
 [197.60239]
 [137.21407]]
70 Cost:  12.087715 
Prediction:
 [[156.19063]
 [181.37471]
 [182.0946 ]
 [197.5993 ]
 [137.22618]]
80 Cost:  12.023738 
Prediction:
 [[156.17732]
 [181.38387]
 [182.09056]
 [197.59624]
 [137.2383 ]]
90 Cost:  11.960162 
Prediction:
 [[156.16406]
 [181.39297]
 [182.08652]
 [197.59317]
 [137.2

In [26]:
import numpy as np

def cost(hypothesis, Y):
    return tf.reduce_mean(tf.square(hypothesis - Y))

#텐서 연산을 위해 함수를 만들어줌
def Hypothesis(X):
    return tf.matmul(X, W) + b

tf.random.set_seed(777) # 메소드 수정

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1] # n개 줄의 처음부터 마지막 한개를 제외 한 것
y_data = xy[:, [-1]] # n개 줄의 마지막 하나만 가져옴

X = tf.constant(x_data, dtype=tf.float32)
Y = tf.constant(y_data, dtype=tf.float32)

W = tf.Variable(tf.random.normal([3, 1]), name='weight3')
b = tf.Variable(tf.random.normal([1]), name='bias')

for step in range(2001):
    with tf.GradientTape() as tape:
        hypothesis = Hypothesis(X)
        curr_cost = cost(hypothesis, y_data)
    gradients = tape.gradient(curr_cost, [W, b])
    optimizer.apply_gradients(grads_and_vars=zip(gradients, [W, b]))

    if step % 10 == 0:
        print(step, "Cost: ", curr_cost.numpy(), "\nPrediction:\n", hypothesis.numpy())

# 예측하려는 새로운 데이터
x1 = [[100, 70, 101]]
x2 = [[60, 70, 110], [90, 100, 80]]

# 새로운 데이터를 텐서로 변환
X1 = tf.constant(x1, dtype=tf.float32)
X2 = tf.constant(x2, dtype=tf.float32)

print("Your score will be ", Hypothesis(X1).numpy())
print("Other scores will be ", Hypothesis(X2).numpy())


0 Cost:  6518.401 
Prediction:
 [[ 80.63533 ]
 [ 98.03138 ]
 [ 96.236145]
 [103.68654 ]
 [ 75.687195]]
10 Cost:  0.53654444 
Prediction:
 [[152.05165]
 [183.87225]
 [180.81465]
 [195.79065]
 [141.16289]]
20 Cost:  0.4754622 
Prediction:
 [[152.26573]
 [184.13335]
 [181.06995]
 [196.06894]
 [141.36276]]
30 Cost:  0.4740517 
Prediction:
 [[152.26437]
 [184.1355 ]
 [181.0701 ]
 [196.06934]
 [141.36511]]
40 Cost:  0.4726472 
Prediction:
 [[152.26239]
 [184.13687]
 [181.06949]
 [196.06894]
 [141.36688]]
50 Cost:  0.47125235 
Prediction:
 [[152.26039]
 [184.13821]
 [181.06886]
 [196.06853]
 [141.36864]]
60 Cost:  0.46985778 
Prediction:
 [[152.25842]
 [184.1396 ]
 [181.06827]
 [196.06812]
 [141.3704 ]]
70 Cost:  0.4684821 
Prediction:
 [[152.25642]
 [184.14091]
 [181.06763]
 [196.0677 ]
 [141.37213]]
80 Cost:  0.46710652 
Prediction:
 [[152.25447]
 [184.14229]
 [181.06703]
 [196.06732]
 [141.37389]]
90 Cost:  0.4657384 
Prediction:
 [[152.2525 ]
 [184.14362]
 [181.0664 ]
 [196.0669 ]
 [141.3

In [30]:
import numpy as np
import tensorflow as tf

def cost(hypothesis, Y):
    return tf.reduce_mean(tf.square(hypothesis - Y))

filename = 'data-01-test-score.csv'
xy = np.loadtxt(filename, delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
batch_size = 10

#한번에 10개씩 가져와서 x_data와 y_data를 dataset에 저장해줌
dataset = tf.data.Dataset.from_tensor_slices((x_data, y_data)).batch(batch_size)

X = tf.keras.Input(shape=(3,), batch_size=None)
Y = tf.keras.Input(shape=(1,), batch_size=None)

W = tf.Variable(tf.random.normal([3, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

optimizer = tf.keras.optimizers.SGD(learning_rate=1e-5)

for step in range(2001):
    for batch_x, batch_y in dataset:    #x_data와 y_data의 값을 순차적으로 batch_x, batch_y에 넣어줌
        with tf.GradientTape() as tape:
            hypothesis = tf.matmul(batch_x, W) + b 
            curr_cost = cost(hypothesis, batch_y)
        grads = tape.gradient(curr_cost, [W, b])
        optimizer.apply_gradients(grads_and_vars=zip(grads, [W, b]))
        if step % 10 == 0:
            print(step, "Cost: ", curr_cost.numpy(), "\nPrediction:\n", hypothesis.numpy())


0 Cost:  52907.906 
Prediction:
 [[-48.65272 ]
 [-63.301323]
 [-59.780552]
 [-66.55337 ]
 [-48.251038]]
10 Cost:  7.414209 
Prediction:
 [[154.80069]
 [181.25368]
 [181.17369]
 [195.84097]
 [138.28659]]
20 Cost:  6.8935175 
Prediction:
 [[155.40619]
 [182.00052]
 [181.89964]
 [196.63272]
 [138.86   ]]
30 Cost:  6.857232 
Prediction:
 [[155.39795]
 [182.0097 ]
 [181.89874]
 [196.63298]
 [138.87073]]
40 Cost:  6.8212104 
Prediction:
 [[155.38788]
 [182.01659]
 [181.89565]
 [196.63081]
 [138.87971]]
50 Cost:  6.785363 
Prediction:
 [[155.37784]
 [182.02348]
 [181.89256]
 [196.62866]
 [138.88867]]
60 Cost:  6.749727 
Prediction:
 [[155.36783]
 [182.03033]
 [181.88948]
 [196.62651]
 [138.89761]]
70 Cost:  6.7142763 
Prediction:
 [[155.35783]
 [182.03717]
 [181.88641]
 [196.62436]
 [138.90652]]
80 Cost:  6.678945 
Prediction:
 [[155.34785]
 [182.04402]
 [181.88335]
 [196.62222]
 [138.91542]]
90 Cost:  6.6438966 
Prediction:
 [[155.33792]
 [182.05081]
 [181.8803 ]
 [196.6201 ]
 [138.92429]]
1