In [8]:
import tensorflow as tf
import numpy as np

def cost_function(real, pred):
    return tf.reduce_mean(-tf.reduce_sum(real * tf.math.log(pred), axis=1))


x_data = np.array([[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]], dtype=np.float32)
#One-hot encoding
y_data = np.array([[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]], dtype=np.float32) 

X = tf.constant(x_data, dtype=tf.float32)
Y = tf.constant(y_data, dtype=tf.float32)
nb_classes = 3

W = tf.Variable(tf.random.normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random.normal([nb_classes]), name='bias')

optimizer = tf.optimizers.SGD(learning_rate=0.1)

for step in range(2001):
    with tf.GradientTape() as tape:
        hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
        cost_val = cost_function(Y, hypothesis)
    grads = tape.gradient(cost_val, [W, b])
    optimizer.apply_gradients(zip(grads, [W, b]))
    if step % 200 == 0:
        print(step, cost_val.numpy())

print('--------------')
# arg_max를 통해 가장 큰 값을 알려줌
def predict(x):
    hypothesis = tf.nn.softmax(tf.matmul(x, W) + b)
    return hypothesis, tf.argmax(hypothesis, 1)

x_test = np.array([[1, 11, 7, 9]], dtype=np.float32)
hypothesis, result = predict(x_test)
print(hypothesis.numpy(), result.numpy())

print('--------------')
x_test = np.array([[1, 3, 4, 3]], dtype=np.float32)
hypothesis, result = predict(x_test)
print(hypothesis.numpy(), result.numpy())

print('--------------')
x_test = np.array([[1, 1, 0, 1]], dtype=np.float32)
hypothesis, result = predict(x_test)
print(hypothesis.numpy(), result.numpy())

print('--------------')
x_test = np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]], dtype=np.float32)
hypothesis, result = predict(x_test)
print(hypothesis.numpy(), result.numpy())


0 5.9159136
200 0.61272615
400 0.49859747
600 0.40537062
800 0.31397146
1000 0.23633836
1200 0.21300653
1400 0.19453388
1600 0.17890894
1800 0.16552944
2000 0.15395182
--------------
[[3.2362987e-03 9.9675328e-01 1.0477415e-05]] [1]
--------------
[[0.8879774  0.09748691 0.01453576]] [0]
--------------
[[1.4548392e-08 3.3704421e-04 9.9966300e-01]] [2]
--------------
[[3.2362987e-03 9.9675328e-01 1.0477435e-05]
 [8.8797742e-01 9.7486906e-02 1.4535764e-02]
 [1.4548392e-08 3.3704421e-04 9.9966300e-01]] [1 0 2]
